# Generated by Django 4.0.4 on 2024-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='ecocontainer82/'),
        ),
    ]
